version: "2"
services:

  calibreimage:
    build: build
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      nproc: 65535
    ports:
      - "5901:5901"
      - "8808:8808"
    volumes:
      - "library:/home/vnc/Calibre Library"
    stdin_open: true

volumes:
  library:
    driver: local
