version: "2"
services:

  calibre:
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "5901:5901"
      - "8088:8088"
    volumes:
      - "library:/ebook"
    stdin_open: true

volumes:
  library:
    driver: local
